version: '3'
services:
#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: rabbitmq
#    hostname: node1
#    ports:
#      - 5672:5672
#      - 15672:15672
#    volumes:
#      - rabbitmq:/var/lib/rabbitmq
  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.8.0
    container_name: filebeat
    depends_on:
      - elasticsearch
    volumes:
      - filebeat:/usr/share/filebeat/data
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../ads_microservice/log:/var/log/ads:ro
      - ../geocoder_microservice/log:/var/log/geocoder:ro
      - ../auth_service/log:/var/log/auth:ro
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.8.0
    container_name: logstash
    depends_on:
      - elasticsearch
    environment:
      LOG_LEVEL: debug
      ELASTICCSEARCH_HOSTS: http://elasticsearch:9200
    volumes:
      - logstash:/usr/share/logstash/data
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - 5000:5000
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0
    command: ["elasticsearch", "-Elogger.level=DEBUG"]
    container_name: elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.8.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      ELASTICCSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
volumes:
#  rabbitmq:
  filebeat:
  logstash:
  elasticsearch:
  kibana:
